import { pgTable, serial, integer, text } from 'drizzle-orm/pg-core';

export const task = pgTable('task', {
	id: serial('id').primaryKey(),
	title: text('title').notNull(),
	priority: integer('priority').notNull().default(1)
});

// Auth schema is generated by a script (see auth:schema).
// Now that it exists in the repo, we can safely re-export it for better-auth.
export * from './auth.schema';
